### ISSUE TITLE
Basic 'Tank' structure

### ISSUE THREAD

**Issue by rodrigo-borges** [rodrigo-borges/qolos#15]
**This is a main hub for the basic Tank structure; minor issues detail each sub-part and are referenced here.**

A tank defines how much a user has stored of a given color. It will be the main property users have, and both mixing, selling and buying colors manipulate its contents. The resolution of volume is liters, so all transactions involving an amount of color is done as integers.

 - [x] (#21) The database structure is a relationship between the User and Color models:

| [PK] id | [FK] user_id | [FK] color_id | capacity | amount |
| --- | --- | --- | --- | --- |
| 1 | 3 | 12 | 1000 | 100 |
| 2 | 3 | 22 | 1000 | 150 |
| ... |

 - [x] (#21) Tanks are created given user and color, and a single user can have a maximum amount of tanks.
 - [x] (#22) Color can be put on and retrieved from a tank, respecting both its capacity and emptiness.
 - [x] (#23) A user can mix two colors they have any amount in tanks, the result being put in a third tank.

*Basic user interaction relates directly to these functionalities, so there may be cross-dependencies.*
