### ISSUE TITLE
Basic 'Color' structure

### ISSUE THREAD

**Issue by rodrigo-borges** [rodrigo-borges/qolos#7]
**This issue will be used as a main hub for the basic Color structure feature. Minor issues will be created for each sub-part of it, and once it happens they should be referenced here accordingly.**

Along with users/players, colors are a main, independent entity in the game. The domain of the game (both its market and mixture possibilities) is a discretized CMY space. For the front-end to actually show the colors, however, there must be a RGB convertion.

 - [x] (#8) Initial proposal for the database (subject to editing in this same post):

| id | c | m | y | rgb |
| --- | --- | --- | --- | --- |
| 1 | 0.0 | 0.0 | 0.0 | #FFFFFF |
| 2 | 1.0 | 0.5 | 0.0 | #0080FF |
| ... |

Besides this basic data, basic functions to be implemented (either inside or outside the model) are:
 - [x] (#8) Given a CMY combination, return the RGB equivalent in hexadecimal representation;
 - [x] (#10) Given a CMY combination, return the closest color on the discretized space;
 - [x] (#11) Given two color objects, along with the proportion of each, return a color that is the mixture of them. The mixture is continuous, but the resulting color is then reduced to the closest discrete one;
 - [x] (#9) Given some distribution parameter, populate the database with colors. This function will be part of the server initialization and will define the domain of a given round of the game.

*Relations involving color, like color tanks, color price or color stock, belong on issues separate from this one.*
